### ISSUE TITLE
Question: what are compexity of map, ap and retract?

### ISSUE THREAD

**Issue by safareli** [ethul/purescript-freeap#7]
I'm interested in what's complexity of map, ap and retract. Is the implementation in spirit of https://www.eyrie.org/~zednenem/2013/05/27/freeapp which uses DList like optimisation?

**Comment by ethul** [comment]
It is timely that you bring this up. I have been working on a branch to
test performance of using the DList optimization mention in that post
compared to the current implementation. I should have an update on this
soon!

**Comment by safareli** [comment]
I'm implementing Free Applicative in https://github.com/safareli/free/pull/31, as I don't understand this implementation quite well, I wanted to know which one is better so that, I could base my port on that.

**Comment by ethul** [comment]
Awesome. Currently, I am not sure which implementation has better
performance in JS, but I will post the results of my benchmarking. However
it might be a few days before I will have a moment to do this.

**Comment by ethul** [comment]
However, since the implementation is similar to the first one described in
the post, the asymptotic performance is most likely as it is described
there (O(n) for map and O(n^2+m) for ap). But I can expand on which one
might better once I work more on the comparison.

**Comment by ethul** [comment]
Added benchmarks in #9. Closing
